# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Abstract Nonsense
email: garrett.figueroa@gmail.com
description: >- # this means to ignore newlines until "locale:"
  Howdy! This is my personal website for assorted interests - math, music, 
  film, baking, bicycling, and whatever else I'd like to connect with folks about.
locale: en-US
domain: "djspacewhale.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://djspacewhale.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  djspacewhale
linkedin_username: garf98
mastodon:
  - username: djspacewhale
    instance: mathstodon.xyz

# Build settings
#theme: minima
remote_theme: "jekyll/minima@v2.5.2" 
plugins:
#  - jekyll-spaceship
  - jekyll-feed
  - jekyll-pdf-embed
  - jekyll-include-cache
#  - jekyll-seo-tag

# enabling plugin to use readme.md for index

#plugins:
#  - jekyll-readme-index

whitelist: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
Exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md

# more settings, from jekyll-bear-theme config
markdown: kramdown

#compress_html:
#  clippings: all
#  comments: [""]
#  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
#  profile: false
#  blanklines: false
#  ignore:
#    envs: []

sass:
  sass_dir: css
  style:    compressed

#collections:
#  my_tags:
#    output: true
#    permalink: /tagged/:slug/
#defaults:
#  -
#    scope:
#      path: ""
#      type: my_tags
#    values:
#      layout: tagged

#permalink: /blog/:slug
#future: false

#exclude: [vendor]

#Blog: /blog

# Add general links to site pages here
#links:
#  Resume: /assets/resume.pdf
  

# Add links for more focus here
special_links:
  "Search": https://duckduckgo.com

# Defaults for posts, enabling MathJax

defaults:
- scope:
    path: "_posts"
  values:
    layout: "posts"

# timezone

timezone: America/Denver